try{
    let resultado=10/0
      }catch(error) {  
        console.error("se produjo un error "+error.message)
}
